using System.Runtime.CompilerServices;
using System.Threading.Tasks;
Console.WriteLine("Введите a"); int a = Convert.ToInt32(Console.ReadLine());
Console.WriteLine("Введите b"); int b = Convert.ToInt32(Console.ReadLine());
Console.WriteLine("Введите c"); int c = Convert.ToInt32(Console.ReadLine());

Console.WriteLine("a^3-3a^2b+3ab^2-b^3 = (a - b)^3");
int answer1 = Convert.ToInt32(Math.Pow(a - b, 3));
Console.WriteLine($"({a} - {b})^3 = {answer1} при а={a}, b={b}");
Console.WriteLine("a^3+3a^2b+3ab^2+b^3 = (a + b)^3");
int answer2 = Convert.ToInt32(Math.Pow(a + b, 3));
Console.WriteLine($"({a} + {b})^3 = {answer2} при а={a}, b={b}");
Console.WriteLine("(a+b)(a^2-ab+b^2) = a^3 + b^3");
int a1 = Convert.ToInt32(Math.Pow(a, 3)); int b1 = Convert.ToInt32(Math.Pow(b, 3));
int answer3 = a1 + b1;
Console.WriteLine($"{a}^3 + {b}^3 = {answer3} при а={a}, b={b}");
Console.WriteLine("(a-b)(a^2+ab+b^2) = a^3 - b^3");
int a2 = Convert.ToInt32(Math.Pow(a, 3)); int b2 = Convert.ToInt32(Math.Pow(b, 3));
int answer4 = a2 - b2;
Console.WriteLine($"{a}^3 - {b}^3 = {answer4} при а={a}, b={b}");
Console.WriteLine("(a - b) * (a + b) = a^2 - b^2");
int a3 = Convert.ToInt32(Math.Pow(a, 2)); int b3 = Convert.ToInt32(Math.Pow(b, 2));
int answer5 = a3 - b3;
Console.WriteLine($"{a}^2 - {b}^2 = {answer5} при а={a}, b={b}");
Console.WriteLine("a^2-2ab+b^2 = (a - b)^2");
int answer6 = Convert.ToInt32(Math.Pow(a - b, 2));
Console.WriteLine($"({a} - {b})^2 = {answer6} при а={a}, b={b}");
Console.WriteLine("a^2+2ab+b^2 = (a + b)^2");
int answer7 = Convert.ToInt32(Math.Pow(a + b, 2));
Console.WriteLine($"({a} + {b})^2 = {answer7} при а={a}, b={b}");
